// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/agent.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AgentInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	User                 string   `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	Entity               string   `protobuf:"bytes,10,opt,name=entity,proto3" json:"entity,omitempty"`
	Tags                 []string `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentInfo) Reset()         { *m = AgentInfo{} }
func (m *AgentInfo) String() string { return proto.CompactTextString(m) }
func (*AgentInfo) ProtoMessage()    {}
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71288b2b6ed4dc, []int{0}
}

func (m *AgentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentInfo.Unmarshal(m, b)
}
func (m *AgentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentInfo.Marshal(b, m, deterministic)
}
func (m *AgentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentInfo.Merge(m, src)
}
func (m *AgentInfo) XXX_Size() int {
	return xxx_messageInfo_AgentInfo.Size(m)
}
func (m *AgentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AgentInfo proto.InternalMessageInfo

func (m *AgentInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *AgentInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AgentInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *AgentInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *AgentInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *AgentInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *AgentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AgentInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AgentInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *AgentInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *AgentInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReqAgentAdd struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Scene                string       `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	Cover                string       `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string       `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Location             string       `protobuf:"bytes,6,opt,name=location,proto3" json:"location,omitempty"`
	Contact              string       `protobuf:"bytes,8,opt,name=contact,proto3" json:"contact,omitempty"`
	Operator             string       `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Address              *AddressInfo `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqAgentAdd) Reset()         { *m = ReqAgentAdd{} }
func (m *ReqAgentAdd) String() string { return proto.CompactTextString(m) }
func (*ReqAgentAdd) ProtoMessage()    {}
func (*ReqAgentAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71288b2b6ed4dc, []int{1}
}

func (m *ReqAgentAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAgentAdd.Unmarshal(m, b)
}
func (m *ReqAgentAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAgentAdd.Marshal(b, m, deterministic)
}
func (m *ReqAgentAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAgentAdd.Merge(m, src)
}
func (m *ReqAgentAdd) XXX_Size() int {
	return xxx_messageInfo_ReqAgentAdd.Size(m)
}
func (m *ReqAgentAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAgentAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAgentAdd proto.InternalMessageInfo

func (m *ReqAgentAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAgentAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqAgentAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqAgentAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqAgentAdd) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ReqAgentAdd) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

func (m *ReqAgentAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqAgentAdd) GetAddress() *AddressInfo {
	if m != nil {
		return m.Address
	}
	return nil
}

type ReqAgentUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string   `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqAgentUpdate) Reset()         { *m = ReqAgentUpdate{} }
func (m *ReqAgentUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqAgentUpdate) ProtoMessage()    {}
func (*ReqAgentUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71288b2b6ed4dc, []int{2}
}

func (m *ReqAgentUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAgentUpdate.Unmarshal(m, b)
}
func (m *ReqAgentUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAgentUpdate.Marshal(b, m, deterministic)
}
func (m *ReqAgentUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAgentUpdate.Merge(m, src)
}
func (m *ReqAgentUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqAgentUpdate.Size(m)
}
func (m *ReqAgentUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAgentUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAgentUpdate proto.InternalMessageInfo

func (m *ReqAgentUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqAgentUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqAgentUpdate) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqAgentUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqAgentUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyAgentOne struct {
	Info                 *AgentInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAgentOne) Reset()         { *m = ReplyAgentOne{} }
func (m *ReplyAgentOne) String() string { return proto.CompactTextString(m) }
func (*ReplyAgentOne) ProtoMessage()    {}
func (*ReplyAgentOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71288b2b6ed4dc, []int{3}
}

func (m *ReplyAgentOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAgentOne.Unmarshal(m, b)
}
func (m *ReplyAgentOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAgentOne.Marshal(b, m, deterministic)
}
func (m *ReplyAgentOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAgentOne.Merge(m, src)
}
func (m *ReplyAgentOne) XXX_Size() int {
	return xxx_messageInfo_ReplyAgentOne.Size(m)
}
func (m *ReplyAgentOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAgentOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAgentOne proto.InternalMessageInfo

func (m *ReplyAgentOne) GetInfo() *AgentInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyAgentOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyAgentList struct {
	Total                uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32       `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32       `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*AgentInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyAgentList) Reset()         { *m = ReplyAgentList{} }
func (m *ReplyAgentList) String() string { return proto.CompactTextString(m) }
func (*ReplyAgentList) ProtoMessage()    {}
func (*ReplyAgentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a71288b2b6ed4dc, []int{4}
}

func (m *ReplyAgentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyAgentList.Unmarshal(m, b)
}
func (m *ReplyAgentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyAgentList.Marshal(b, m, deterministic)
}
func (m *ReplyAgentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyAgentList.Merge(m, src)
}
func (m *ReplyAgentList) XXX_Size() int {
	return xxx_messageInfo_ReplyAgentList.Size(m)
}
func (m *ReplyAgentList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyAgentList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyAgentList proto.InternalMessageInfo

func (m *ReplyAgentList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyAgentList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyAgentList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyAgentList) GetList() []*AgentInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyAgentList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentInfo)(nil), "omo.msp.assignment.AgentInfo")
	proto.RegisterType((*ReqAgentAdd)(nil), "omo.msp.assignment.ReqAgentAdd")
	proto.RegisterType((*ReqAgentUpdate)(nil), "omo.msp.assignment.ReqAgentUpdate")
	proto.RegisterType((*ReplyAgentOne)(nil), "omo.msp.assignment.ReplyAgentOne")
	proto.RegisterType((*ReplyAgentList)(nil), "omo.msp.assignment.ReplyAgentList")
}

func init() {
	proto.RegisterFile("proto/assignment/agent.proto", fileDescriptor_4a71288b2b6ed4dc)
}

var fileDescriptor_4a71288b2b6ed4dc = []byte{
	// 616 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0xcd, 0x26, 0x9b, 0xb4, 0x3b, 0x69, 0x4b, 0x65, 0x21, 0xb4, 0x8a, 0xa8, 0x48, 0xf7, 0xd4,
	0x53, 0x2a, 0xca, 0x01, 0x71, 0x4c, 0x0f, 0x54, 0x48, 0xb4, 0x08, 0x17, 0x84, 0xd4, 0x9b, 0xd9,
	0x9d, 0x46, 0x16, 0x59, 0x3b, 0xac, 0x9d, 0x96, 0x8a, 0x0b, 0x12, 0xff, 0xc6, 0x4f, 0xf0, 0x17,
	0x7c, 0x01, 0xf2, 0x38, 0x5e, 0x9a, 0xb4, 0x09, 0x41, 0xdc, 0xfc, 0x3c, 0x6f, 0xdf, 0xcc, 0x7b,
	0xe3, 0x28, 0xf0, 0x78, 0x52, 0x69, 0xab, 0x0f, 0x85, 0x31, 0x72, 0xa4, 0x4a, 0x54, 0xf6, 0x50,
	0x8c, 0x50, 0xd9, 0x01, 0x5d, 0x33, 0xa6, 0x4b, 0x3d, 0x28, 0xcd, 0x64, 0xf0, 0xa7, 0xde, 0xdb,
	0xbb, 0xf3, 0x45, 0xae, 0xcb, 0x52, 0x2b, 0xff, 0x49, 0xf6, 0xbd, 0x09, 0xc9, 0xd0, 0x49, 0xbc,
	0x52, 0x97, 0x9a, 0xed, 0x42, 0x6b, 0x2a, 0x8b, 0x34, 0xea, 0x47, 0x07, 0x09, 0x77, 0x47, 0xb6,
	0x03, 0x4d, 0x59, 0xa4, 0xcd, 0x7e, 0x74, 0x10, 0xf3, 0xa6, 0x2c, 0x58, 0x0a, 0x1b, 0x79, 0x85,
	0xc2, 0x62, 0x91, 0xb6, 0xfa, 0xd1, 0x41, 0x8b, 0x07, 0xe8, 0x2a, 0xd3, 0x49, 0x41, 0x95, 0xd8,
	0x57, 0x66, 0xb0, 0xfe, 0x46, 0x57, 0x69, 0x9b, 0x94, 0x03, 0x64, 0x3d, 0xd8, 0xd4, 0x13, 0xac,
	0xa8, 0xd4, 0xa1, 0x52, 0x8d, 0x19, 0x83, 0x58, 0x89, 0x12, 0xd3, 0x0d, 0xba, 0xa7, 0x33, 0x7b,
	0x04, 0x9d, 0x0a, 0x4b, 0x51, 0x7d, 0x4a, 0x37, 0xe9, 0x76, 0x86, 0x1c, 0x77, 0x6a, 0xb0, 0x4a,
	0x13, 0xcf, 0x75, 0x67, 0xc7, 0x45, 0x65, 0xa5, 0xbd, 0x49, 0xc1, 0x73, 0x3d, 0x72, 0x5c, 0x2b,
	0x46, 0x26, 0xed, 0xf6, 0x5b, 0x8e, 0xeb, 0xce, 0xd9, 0xaf, 0x08, 0xba, 0x1c, 0x3f, 0x53, 0x10,
	0xc3, 0xa2, 0xa8, 0x7b, 0x47, 0xb7, 0x7a, 0x3f, 0x84, 0xb6, 0xc9, 0x51, 0x21, 0x85, 0x91, 0x70,
	0x0f, 0xdc, 0x6d, 0xae, 0xaf, 0xb0, 0xa2, 0x34, 0x12, 0xee, 0xc1, 0xad, 0x39, 0xdb, 0x73, 0x73,
	0xf6, 0x60, 0x73, 0xac, 0x73, 0x61, 0xa5, 0x56, 0xc1, 0x6f, 0xc0, 0x94, 0x92, 0x56, 0x56, 0xe4,
	0x76, 0x66, 0x2e, 0xc0, 0xb9, 0x94, 0x92, 0x85, 0x94, 0x5e, 0xc0, 0x86, 0x28, 0x8a, 0x0a, 0x8d,
	0x21, 0x9b, 0xdd, 0xa3, 0x27, 0x83, 0xbb, 0x8f, 0x60, 0x30, 0xf4, 0x14, 0xb7, 0x63, 0x1e, 0xf8,
	0xd9, 0xb7, 0x08, 0x76, 0x82, 0xe9, 0xf7, 0xb4, 0xaa, 0x7b, 0xf6, 0x1f, 0x92, 0x68, 0xce, 0x27,
	0xb1, 0xd2, 0x73, 0xbc, 0xe8, 0xb9, 0x9e, 0xbe, 0x3d, 0x3f, 0x7d, 0xf6, 0x15, 0xb6, 0x39, 0x4e,
	0xc6, 0x37, 0x34, 0xc3, 0x1b, 0x85, 0xec, 0x29, 0xc4, 0x52, 0x5d, 0x6a, 0x9a, 0xa0, 0x7b, 0xb4,
	0x77, 0xaf, 0x97, 0xf0, 0x5a, 0x39, 0x51, 0xd9, 0x73, 0xe8, 0x18, 0x2b, 0xec, 0xd4, 0xd0, 0x8c,
	0x4b, 0x02, 0xa0, 0x2e, 0xe7, 0x44, 0xe3, 0x33, 0x7a, 0xf6, 0x83, 0xfc, 0x87, 0xee, 0xaf, 0xa5,
	0xb1, 0xce, 0x99, 0xd5, 0x56, 0x8c, 0xa9, 0xff, 0x36, 0xf7, 0xc0, 0x6d, 0x66, 0x22, 0x46, 0x78,
	0x2a, 0xbe, 0x50, 0x8b, 0x6d, 0x1e, 0x60, 0xa8, 0x9c, 0xe9, 0x6b, 0xca, 0x62, 0x56, 0x39, 0xd3,
	0xd7, 0xce, 0xc8, 0x58, 0x1a, 0x9b, 0xc6, 0xfd, 0xd6, 0x1a, 0x46, 0x1c, 0xf5, 0x96, 0x91, 0xf6,
	0x3f, 0x19, 0x39, 0xfa, 0x19, 0xc3, 0x16, 0x89, 0x9d, 0x63, 0x75, 0x25, 0x73, 0x64, 0x67, 0xd0,
	0x19, 0x16, 0x85, 0xcb, 0x73, 0x89, 0x46, 0xfd, 0xd2, 0x7b, 0xfb, 0x4b, 0x9b, 0x84, 0x9d, 0x64,
	0x0d, 0xa7, 0x77, 0x82, 0x76, 0x95, 0xde, 0x14, 0x0d, 0x59, 0x59, 0x4f, 0xef, 0x14, 0x12, 0x8e,
	0xa5, 0xbe, 0xc2, 0xb5, 0x24, 0xf7, 0x96, 0x4a, 0xba, 0x72, 0xd6, 0x60, 0x17, 0xf0, 0xe0, 0x04,
	0x69, 0x81, 0xc7, 0x37, 0x2f, 0xe5, 0xd8, 0x62, 0xc5, 0xf6, 0x57, 0x88, 0x7a, 0x4a, 0x2f, 0x5b,
	0x3d, 0xa9, 0x93, 0xcb, 0x1a, 0xec, 0x03, 0x6c, 0x9d, 0xa0, 0x75, 0x81, 0x4b, 0x63, 0x65, 0xfe,
	0x7f, 0xc2, 0xb5, 0x4c, 0xd6, 0x60, 0x6f, 0x01, 0xfc, 0x8f, 0xee, 0x58, 0x18, 0x64, 0xd9, 0xaa,
	0x3d, 0x79, 0xde, 0xdf, 0x73, 0x78, 0x07, 0x3b, 0x33, 0xc9, 0x75, 0x62, 0x58, 0x53, 0xf5, 0x98,
	0x5d, 0xec, 0x2e, 0xfe, 0x85, 0x7c, 0xec, 0xd0, 0xcd, 0xb3, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xbc, 0x16, 0xa4, 0xbe, 0x8f, 0x06, 0x00, 0x00,
}
