// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/apply.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ApplyInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Type                 uint32   `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	Applicant            string   `protobuf:"bytes,9,opt,name=applicant,proto3" json:"applicant,omitempty"`
	Inviter              string   `protobuf:"bytes,10,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Owner                string   `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                string   `protobuf:"bytes,12,opt,name=group,proto3" json:"group,omitempty"`
	Reason               string   `protobuf:"bytes,13,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyInfo) Reset()         { *m = ApplyInfo{} }
func (m *ApplyInfo) String() string { return proto.CompactTextString(m) }
func (*ApplyInfo) ProtoMessage()    {}
func (*ApplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b4b1cbfe13464c, []int{0}
}

func (m *ApplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyInfo.Unmarshal(m, b)
}
func (m *ApplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyInfo.Marshal(b, m, deterministic)
}
func (m *ApplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyInfo.Merge(m, src)
}
func (m *ApplyInfo) XXX_Size() int {
	return xxx_messageInfo_ApplyInfo.Size(m)
}
func (m *ApplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyInfo proto.InternalMessageInfo

func (m *ApplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ApplyInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplyInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ApplyInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ApplyInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ApplyInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ApplyInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ApplyInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ApplyInfo) GetApplicant() string {
	if m != nil {
		return m.Applicant
	}
	return ""
}

func (m *ApplyInfo) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *ApplyInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ApplyInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ApplyInfo) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type ReqApplyAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                string   `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	Applicant            string   `protobuf:"bytes,4,opt,name=applicant,proto3" json:"applicant,omitempty"`
	Inviter              string   `protobuf:"bytes,5,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqApplyAdd) Reset()         { *m = ReqApplyAdd{} }
func (m *ReqApplyAdd) String() string { return proto.CompactTextString(m) }
func (*ReqApplyAdd) ProtoMessage()    {}
func (*ReqApplyAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b4b1cbfe13464c, []int{1}
}

func (m *ReqApplyAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqApplyAdd.Unmarshal(m, b)
}
func (m *ReqApplyAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqApplyAdd.Marshal(b, m, deterministic)
}
func (m *ReqApplyAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqApplyAdd.Merge(m, src)
}
func (m *ReqApplyAdd) XXX_Size() int {
	return xxx_messageInfo_ReqApplyAdd.Size(m)
}
func (m *ReqApplyAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqApplyAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqApplyAdd proto.InternalMessageInfo

func (m *ReqApplyAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqApplyAdd) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ReqApplyAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqApplyAdd) GetApplicant() string {
	if m != nil {
		return m.Applicant
	}
	return ""
}

func (m *ReqApplyAdd) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *ReqApplyAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyApplyOne struct {
	Info                 *ApplyInfo   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyApplyOne) Reset()         { *m = ReplyApplyOne{} }
func (m *ReplyApplyOne) String() string { return proto.CompactTextString(m) }
func (*ReplyApplyOne) ProtoMessage()    {}
func (*ReplyApplyOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b4b1cbfe13464c, []int{2}
}

func (m *ReplyApplyOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyApplyOne.Unmarshal(m, b)
}
func (m *ReplyApplyOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyApplyOne.Marshal(b, m, deterministic)
}
func (m *ReplyApplyOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyApplyOne.Merge(m, src)
}
func (m *ReplyApplyOne) XXX_Size() int {
	return xxx_messageInfo_ReplyApplyOne.Size(m)
}
func (m *ReplyApplyOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyApplyOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyApplyOne proto.InternalMessageInfo

func (m *ReplyApplyOne) GetInfo() *ApplyInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyApplyOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyApplyList struct {
	Total                uint32       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32       `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32       `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*ApplyInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyApplyList) Reset()         { *m = ReplyApplyList{} }
func (m *ReplyApplyList) String() string { return proto.CompactTextString(m) }
func (*ReplyApplyList) ProtoMessage()    {}
func (*ReplyApplyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_93b4b1cbfe13464c, []int{3}
}

func (m *ReplyApplyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyApplyList.Unmarshal(m, b)
}
func (m *ReplyApplyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyApplyList.Marshal(b, m, deterministic)
}
func (m *ReplyApplyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyApplyList.Merge(m, src)
}
func (m *ReplyApplyList) XXX_Size() int {
	return xxx_messageInfo_ReplyApplyList.Size(m)
}
func (m *ReplyApplyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyApplyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyApplyList proto.InternalMessageInfo

func (m *ReplyApplyList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyApplyList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyApplyList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyApplyList) GetList() []*ApplyInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyApplyList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*ApplyInfo)(nil), "omo.msp.assignment.ApplyInfo")
	proto.RegisterType((*ReqApplyAdd)(nil), "omo.msp.assignment.ReqApplyAdd")
	proto.RegisterType((*ReplyApplyOne)(nil), "omo.msp.assignment.ReplyApplyOne")
	proto.RegisterType((*ReplyApplyList)(nil), "omo.msp.assignment.ReplyApplyList")
}

func init() {
	proto.RegisterFile("proto/assignment/apply.proto", fileDescriptor_93b4b1cbfe13464c)
}

var fileDescriptor_93b4b1cbfe13464c = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x1d, 0x27, 0x6d, 0xa6, 0x49, 0xa8, 0x56, 0x08, 0xad, 0xa2, 0x46, 0xa4, 0x3e, 0xe5,
	0x94, 0x8a, 0x72, 0xe0, 0x9c, 0x1e, 0x1a, 0x21, 0xd1, 0x22, 0x39, 0x20, 0xa4, 0xde, 0x4c, 0x3c,
	0x8d, 0x56, 0x8a, 0xbd, 0xc6, 0xde, 0xa4, 0x44, 0x3c, 0x0d, 0x4f, 0xc2, 0x8d, 0xb7, 0xe0, 0x5d,
	0xd0, 0xcc, 0xc6, 0x4e, 0xa1, 0x8d, 0x1b, 0xc4, 0xcd, 0xdf, 0xfc, 0x7c, 0x33, 0xdf, 0xb7, 0x23,
	0xc3, 0x49, 0x9a, 0x69, 0xa3, 0xcf, 0xc2, 0x3c, 0x57, 0xf3, 0x24, 0xc6, 0xc4, 0x9c, 0x85, 0x69,
	0xba, 0x58, 0x8f, 0x38, 0x2c, 0x84, 0x8e, 0xf5, 0x28, 0xce, 0xd3, 0xd1, 0x36, 0xdf, 0xeb, 0x3f,
	0xe8, 0x98, 0xe9, 0x38, 0xd6, 0x89, 0x6d, 0xf1, 0x7f, 0xb8, 0xd0, 0x1a, 0x13, 0xc5, 0xdb, 0xe4,
	0x56, 0x8b, 0x63, 0xa8, 0x2f, 0x55, 0x24, 0x9d, 0x81, 0x33, 0x6c, 0x05, 0xf4, 0x29, 0xba, 0xe0,
	0xaa, 0x48, 0xba, 0x03, 0x67, 0xe8, 0x05, 0xae, 0x8a, 0x84, 0x84, 0x83, 0x59, 0x86, 0xa1, 0xc1,
	0x48, 0xd6, 0x07, 0xce, 0xb0, 0x1e, 0x14, 0x90, 0x32, 0xcb, 0x34, 0xe2, 0x8c, 0x67, 0x33, 0x1b,
	0x58, 0xf6, 0xe8, 0x4c, 0x36, 0x98, 0xb9, 0x80, 0xa2, 0x07, 0x87, 0x3a, 0xc5, 0x8c, 0x53, 0x4d,
	0x4e, 0x95, 0x58, 0xbc, 0x80, 0x66, 0x6e, 0x42, 0xb3, 0xcc, 0xe5, 0xc1, 0xc0, 0x19, 0x76, 0x82,
	0x0d, 0x12, 0x02, 0x3c, 0xb3, 0x4e, 0x51, 0x1e, 0x72, 0x94, 0xbf, 0xc5, 0x09, 0xb4, 0xc8, 0x07,
	0x35, 0x0b, 0x13, 0x23, 0x5b, 0x4c, 0xb4, 0x0d, 0xd0, 0x7c, 0x95, 0xac, 0x94, 0xc1, 0x4c, 0x82,
	0x9d, 0xbf, 0x81, 0xe2, 0x39, 0x34, 0xf4, 0x5d, 0x82, 0x99, 0x3c, 0xe2, 0xb8, 0x05, 0x14, 0x9d,
	0x67, 0x7a, 0x99, 0xca, 0xb6, 0x8d, 0x32, 0xa0, 0x7d, 0x32, 0x0c, 0x73, 0x9d, 0xc8, 0x0e, 0x87,
	0x37, 0xc8, 0xff, 0xee, 0xc0, 0x51, 0x80, 0x5f, 0xd8, 0xc4, 0x71, 0x14, 0x6d, 0x39, 0x9d, 0x47,
	0x39, 0xdd, 0xfb, 0x9c, 0x85, 0x96, 0xfa, 0x2e, 0x2d, 0x5e, 0x85, 0x96, 0xc6, 0x9f, 0x5a, 0x2a,
	0xbc, 0xf4, 0xbf, 0x41, 0x27, 0x40, 0xda, 0x8f, 0x96, 0x7c, 0x9f, 0xa0, 0x78, 0x05, 0x9e, 0x4a,
	0x6e, 0x35, 0xef, 0x78, 0x74, 0xde, 0x1f, 0x3d, 0x3c, 0x9c, 0x51, 0x79, 0x15, 0x01, 0x97, 0x8a,
	0x37, 0xe5, 0x7b, 0xb8, 0xdc, 0xf4, 0xf2, 0xb1, 0x26, 0x9e, 0x32, 0xe5, 0xb2, 0xe2, 0xc1, 0xfc,
	0x9f, 0x0e, 0x74, 0xb7, 0xd3, 0xdf, 0xa9, 0xdc, 0x90, 0x1b, 0x46, 0x9b, 0x70, 0xc1, 0xf3, 0x3b,
	0x81, 0x05, 0xa4, 0x2d, 0x0d, 0xe7, 0x78, 0x15, 0x7e, 0xe5, 0x11, 0x9d, 0xa0, 0x80, 0x45, 0xe6,
	0x5a, 0xdf, 0x6d, 0xac, 0x2a, 0x20, 0x09, 0x59, 0xa8, 0x9c, 0x8c, 0xaa, 0xef, 0x21, 0x84, 0x4a,
	0xef, 0x09, 0x69, 0xfc, 0x93, 0x90, 0xf3, 0x5f, 0x1e, 0xb4, 0x99, 0x6c, 0x8a, 0xd9, 0x4a, 0xcd,
	0x50, 0x5c, 0x43, 0x73, 0x1c, 0x45, 0xe4, 0xe7, 0x0e, 0x8e, 0xf2, 0x2a, 0x7a, 0xa7, 0x3b, 0x87,
	0x14, 0x6f, 0xe2, 0xd7, 0x88, 0x6f, 0x82, 0xa6, 0x8a, 0x6f, 0x89, 0xb9, 0x21, 0x29, 0xfb, 0xf1,
	0x5d, 0x41, 0x2b, 0xc0, 0x58, 0xaf, 0x70, 0x2f, 0xca, 0xfe, 0x4e, 0x4a, 0x4a, 0xfb, 0x35, 0x71,
	0x03, 0xcf, 0x26, 0x68, 0xe8, 0x01, 0x2f, 0xd6, 0x97, 0x6a, 0x41, 0x47, 0x77, 0x5a, 0x41, 0x6a,
	0x4b, 0x7a, 0x7e, 0xf5, 0xa6, 0x44, 0xe7, 0xd7, 0xc4, 0x27, 0x68, 0x4f, 0xd0, 0x90, 0xe1, 0x2a,
	0x37, 0x6a, 0xf6, 0x7f, 0xc4, 0x25, 0x8d, 0x5f, 0x13, 0x1f, 0xa0, 0xfb, 0x91, 0xff, 0x43, 0x7b,
	0xed, 0x6c, 0x4b, 0x9f, 0xb6, 0x62, 0x0a, 0x6d, 0x5b, 0x6a, 0x4f, 0x44, 0xf8, 0x95, 0xe6, 0x9a,
	0xcb, 0x45, 0x38, 0x7f, 0x92, 0xf4, 0x42, 0xdc, 0x1c, 0xff, 0xfd, 0xb3, 0xfe, 0xdc, 0xe4, 0xc8,
	0xeb, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x03, 0x70, 0x78, 0xbc, 0xf9, 0x05, 0x00, 0x00,
}
