// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/assignment/apply.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ApplyService service

type ApplyService interface {
	AddOne(ctx context.Context, in *ReqApplyAdd, opts ...client.CallOption) (*ReplyApplyOne, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyApplyOne, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
	GetListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyApplyList, error)
	GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error)
	UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	UpdateStatus(ctx context.Context, in *RequestIntFlag, opts ...client.CallOption) (*ReplyInfo, error)
}

type applyService struct {
	c    client.Client
	name string
}

func NewApplyService(name string, c client.Client) ApplyService {
	return &applyService{
		c:    c,
		name: name,
	}
}

func (c *applyService) AddOne(ctx context.Context, in *ReqApplyAdd, opts ...client.CallOption) (*ReplyApplyOne, error) {
	req := c.c.NewRequest(c.name, "ApplyService.AddOne", in)
	out := new(ReplyApplyOne)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyApplyOne, error) {
	req := c.c.NewRequest(c.name, "ApplyService.GetOne", in)
	out := new(ReplyApplyOne)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "ApplyService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) GetListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyApplyList, error) {
	req := c.c.NewRequest(c.name, "ApplyService.GetListByFilter", in)
	out := new(ReplyApplyList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "ApplyService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "ApplyService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *applyService) UpdateStatus(ctx context.Context, in *RequestIntFlag, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "ApplyService.UpdateStatus", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApplyService service

type ApplyServiceHandler interface {
	AddOne(context.Context, *ReqApplyAdd, *ReplyApplyOne) error
	GetOne(context.Context, *RequestInfo, *ReplyApplyOne) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
	GetListByFilter(context.Context, *RequestFilter, *ReplyApplyList) error
	GetStatistic(context.Context, *RequestFilter, *ReplyStatistic) error
	UpdateByFilter(context.Context, *RequestUpdate, *ReplyInfo) error
	UpdateStatus(context.Context, *RequestIntFlag, *ReplyInfo) error
}

func RegisterApplyServiceHandler(s server.Server, hdlr ApplyServiceHandler, opts ...server.HandlerOption) error {
	type applyService interface {
		AddOne(ctx context.Context, in *ReqApplyAdd, out *ReplyApplyOne) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyApplyOne) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
		GetListByFilter(ctx context.Context, in *RequestFilter, out *ReplyApplyList) error
		GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error
		UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error
		UpdateStatus(ctx context.Context, in *RequestIntFlag, out *ReplyInfo) error
	}
	type ApplyService struct {
		applyService
	}
	h := &applyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&ApplyService{h}, opts...))
}

type applyServiceHandler struct {
	ApplyServiceHandler
}

func (h *applyServiceHandler) AddOne(ctx context.Context, in *ReqApplyAdd, out *ReplyApplyOne) error {
	return h.ApplyServiceHandler.AddOne(ctx, in, out)
}

func (h *applyServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyApplyOne) error {
	return h.ApplyServiceHandler.GetOne(ctx, in, out)
}

func (h *applyServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.ApplyServiceHandler.RemoveOne(ctx, in, out)
}

func (h *applyServiceHandler) GetListByFilter(ctx context.Context, in *RequestFilter, out *ReplyApplyList) error {
	return h.ApplyServiceHandler.GetListByFilter(ctx, in, out)
}

func (h *applyServiceHandler) GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error {
	return h.ApplyServiceHandler.GetStatistic(ctx, in, out)
}

func (h *applyServiceHandler) UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error {
	return h.ApplyServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *applyServiceHandler) UpdateStatus(ctx context.Context, in *RequestIntFlag, out *ReplyInfo) error {
	return h.ApplyServiceHandler.UpdateStatus(ctx, in, out)
}
