// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/assignment/family.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for FamilyService service

type FamilyService interface {
	AddOne(ctx context.Context, in *ReqFamilyAdd, opts ...client.CallOption) (*ReplyFamilyInfo, error)
	UpdateBase(ctx context.Context, in *ReqFamilyUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error)
	GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFamilyInfo, error)
	GetOneByFilter(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFamilyInfo, error)
	GetListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyFamilyList, error)
	GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error)
	UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error)
	UpdateStatus(ctx context.Context, in *RequestIntFlag, opts ...client.CallOption) (*ReplyInfo, error)
	AppendMember(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyList, error)
	SubtractMember(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyList, error)
}

type familyService struct {
	c    client.Client
	name string
}

func NewFamilyService(name string, c client.Client) FamilyService {
	return &familyService{
		c:    c,
		name: name,
	}
}

func (c *familyService) AddOne(ctx context.Context, in *ReqFamilyAdd, opts ...client.CallOption) (*ReplyFamilyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.AddOne", in)
	out := new(ReplyFamilyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) UpdateBase(ctx context.Context, in *ReqFamilyUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.UpdateBase", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) RemoveOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.RemoveOne", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) GetOne(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFamilyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.GetOne", in)
	out := new(ReplyFamilyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) GetOneByFilter(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyFamilyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.GetOneByFilter", in)
	out := new(ReplyFamilyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) GetListByFilter(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyFamilyList, error) {
	req := c.c.NewRequest(c.name, "FamilyService.GetListByFilter", in)
	out := new(ReplyFamilyList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) GetStatistic(ctx context.Context, in *RequestFilter, opts ...client.CallOption) (*ReplyStatistic, error) {
	req := c.c.NewRequest(c.name, "FamilyService.GetStatistic", in)
	out := new(ReplyStatistic)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) UpdateByFilter(ctx context.Context, in *RequestUpdate, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.UpdateByFilter", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) UpdateStatus(ctx context.Context, in *RequestIntFlag, opts ...client.CallOption) (*ReplyInfo, error) {
	req := c.c.NewRequest(c.name, "FamilyService.UpdateStatus", in)
	out := new(ReplyInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) AppendMember(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyList, error) {
	req := c.c.NewRequest(c.name, "FamilyService.AppendMember", in)
	out := new(ReplyList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *familyService) SubtractMember(ctx context.Context, in *RequestInfo, opts ...client.CallOption) (*ReplyList, error) {
	req := c.c.NewRequest(c.name, "FamilyService.SubtractMember", in)
	out := new(ReplyList)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FamilyService service

type FamilyServiceHandler interface {
	AddOne(context.Context, *ReqFamilyAdd, *ReplyFamilyInfo) error
	UpdateBase(context.Context, *ReqFamilyUpdate, *ReplyInfo) error
	RemoveOne(context.Context, *RequestInfo, *ReplyInfo) error
	GetOne(context.Context, *RequestInfo, *ReplyFamilyInfo) error
	GetOneByFilter(context.Context, *RequestInfo, *ReplyFamilyInfo) error
	GetListByFilter(context.Context, *RequestFilter, *ReplyFamilyList) error
	GetStatistic(context.Context, *RequestFilter, *ReplyStatistic) error
	UpdateByFilter(context.Context, *RequestUpdate, *ReplyInfo) error
	UpdateStatus(context.Context, *RequestIntFlag, *ReplyInfo) error
	AppendMember(context.Context, *RequestInfo, *ReplyList) error
	SubtractMember(context.Context, *RequestInfo, *ReplyList) error
}

func RegisterFamilyServiceHandler(s server.Server, hdlr FamilyServiceHandler, opts ...server.HandlerOption) error {
	type familyService interface {
		AddOne(ctx context.Context, in *ReqFamilyAdd, out *ReplyFamilyInfo) error
		UpdateBase(ctx context.Context, in *ReqFamilyUpdate, out *ReplyInfo) error
		RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error
		GetOne(ctx context.Context, in *RequestInfo, out *ReplyFamilyInfo) error
		GetOneByFilter(ctx context.Context, in *RequestInfo, out *ReplyFamilyInfo) error
		GetListByFilter(ctx context.Context, in *RequestFilter, out *ReplyFamilyList) error
		GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error
		UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error
		UpdateStatus(ctx context.Context, in *RequestIntFlag, out *ReplyInfo) error
		AppendMember(ctx context.Context, in *RequestInfo, out *ReplyList) error
		SubtractMember(ctx context.Context, in *RequestInfo, out *ReplyList) error
	}
	type FamilyService struct {
		familyService
	}
	h := &familyServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FamilyService{h}, opts...))
}

type familyServiceHandler struct {
	FamilyServiceHandler
}

func (h *familyServiceHandler) AddOne(ctx context.Context, in *ReqFamilyAdd, out *ReplyFamilyInfo) error {
	return h.FamilyServiceHandler.AddOne(ctx, in, out)
}

func (h *familyServiceHandler) UpdateBase(ctx context.Context, in *ReqFamilyUpdate, out *ReplyInfo) error {
	return h.FamilyServiceHandler.UpdateBase(ctx, in, out)
}

func (h *familyServiceHandler) RemoveOne(ctx context.Context, in *RequestInfo, out *ReplyInfo) error {
	return h.FamilyServiceHandler.RemoveOne(ctx, in, out)
}

func (h *familyServiceHandler) GetOne(ctx context.Context, in *RequestInfo, out *ReplyFamilyInfo) error {
	return h.FamilyServiceHandler.GetOne(ctx, in, out)
}

func (h *familyServiceHandler) GetOneByFilter(ctx context.Context, in *RequestInfo, out *ReplyFamilyInfo) error {
	return h.FamilyServiceHandler.GetOneByFilter(ctx, in, out)
}

func (h *familyServiceHandler) GetListByFilter(ctx context.Context, in *RequestFilter, out *ReplyFamilyList) error {
	return h.FamilyServiceHandler.GetListByFilter(ctx, in, out)
}

func (h *familyServiceHandler) GetStatistic(ctx context.Context, in *RequestFilter, out *ReplyStatistic) error {
	return h.FamilyServiceHandler.GetStatistic(ctx, in, out)
}

func (h *familyServiceHandler) UpdateByFilter(ctx context.Context, in *RequestUpdate, out *ReplyInfo) error {
	return h.FamilyServiceHandler.UpdateByFilter(ctx, in, out)
}

func (h *familyServiceHandler) UpdateStatus(ctx context.Context, in *RequestIntFlag, out *ReplyInfo) error {
	return h.FamilyServiceHandler.UpdateStatus(ctx, in, out)
}

func (h *familyServiceHandler) AppendMember(ctx context.Context, in *RequestInfo, out *ReplyList) error {
	return h.FamilyServiceHandler.AppendMember(ctx, in, out)
}

func (h *familyServiceHandler) SubtractMember(ctx context.Context, in *RequestInfo, out *ReplyList) error {
	return h.FamilyServiceHandler.SubtractMember(ctx, in, out)
}
