// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/meeting.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MeetingInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,4,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,5,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Type                 uint32   `protobuf:"varint,8,opt,name=type,proto3" json:"type,omitempty"`
	Stopped              int64    `protobuf:"varint,9,opt,name=stopped,proto3" json:"stopped,omitempty"`
	Started              int64    `protobuf:"varint,10,opt,name=started,proto3" json:"started,omitempty"`
	Owner                string   `protobuf:"bytes,11,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                string   `protobuf:"bytes,12,opt,name=group,proto3" json:"group,omitempty"`
	Location             string   `protobuf:"bytes,13,opt,name=location,proto3" json:"location,omitempty"`
	Duration             uint32   `protobuf:"varint,14,opt,name=duration,proto3" json:"duration,omitempty"`
	Appointed            string   `protobuf:"bytes,15,opt,name=appointed,proto3" json:"appointed,omitempty"`
	Name                 string   `protobuf:"bytes,16,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,17,opt,name=remark,proto3" json:"remark,omitempty"`
	Signs                []string `protobuf:"bytes,20,rep,name=signs,proto3" json:"signs,omitempty"`
	Submits              []string `protobuf:"bytes,21,rep,name=submits,proto3" json:"submits,omitempty"`
	Notifies             []string `protobuf:"bytes,22,rep,name=notifies,proto3" json:"notifies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeetingInfo) Reset()         { *m = MeetingInfo{} }
func (m *MeetingInfo) String() string { return proto.CompactTextString(m) }
func (*MeetingInfo) ProtoMessage()    {}
func (*MeetingInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ac28e9a2c56839, []int{0}
}

func (m *MeetingInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeetingInfo.Unmarshal(m, b)
}
func (m *MeetingInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeetingInfo.Marshal(b, m, deterministic)
}
func (m *MeetingInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeetingInfo.Merge(m, src)
}
func (m *MeetingInfo) XXX_Size() int {
	return xxx_messageInfo_MeetingInfo.Size(m)
}
func (m *MeetingInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MeetingInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MeetingInfo proto.InternalMessageInfo

func (m *MeetingInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *MeetingInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MeetingInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *MeetingInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *MeetingInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MeetingInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MeetingInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MeetingInfo) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MeetingInfo) GetStopped() int64 {
	if m != nil {
		return m.Stopped
	}
	return 0
}

func (m *MeetingInfo) GetStarted() int64 {
	if m != nil {
		return m.Started
	}
	return 0
}

func (m *MeetingInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MeetingInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *MeetingInfo) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *MeetingInfo) GetDuration() uint32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MeetingInfo) GetAppointed() string {
	if m != nil {
		return m.Appointed
	}
	return ""
}

func (m *MeetingInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MeetingInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *MeetingInfo) GetSigns() []string {
	if m != nil {
		return m.Signs
	}
	return nil
}

func (m *MeetingInfo) GetSubmits() []string {
	if m != nil {
		return m.Submits
	}
	return nil
}

func (m *MeetingInfo) GetNotifies() []string {
	if m != nil {
		return m.Notifies
	}
	return nil
}

type ReqMeetingAdd struct {
	Type                 uint32   `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Appointed            string   `protobuf:"bytes,6,opt,name=appointed,proto3" json:"appointed,omitempty"`
	Location             string   `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Operator             string   `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMeetingAdd) Reset()         { *m = ReqMeetingAdd{} }
func (m *ReqMeetingAdd) String() string { return proto.CompactTextString(m) }
func (*ReqMeetingAdd) ProtoMessage()    {}
func (*ReqMeetingAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ac28e9a2c56839, []int{1}
}

func (m *ReqMeetingAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMeetingAdd.Unmarshal(m, b)
}
func (m *ReqMeetingAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMeetingAdd.Marshal(b, m, deterministic)
}
func (m *ReqMeetingAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMeetingAdd.Merge(m, src)
}
func (m *ReqMeetingAdd) XXX_Size() int {
	return xxx_messageInfo_ReqMeetingAdd.Size(m)
}
func (m *ReqMeetingAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMeetingAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMeetingAdd proto.InternalMessageInfo

func (m *ReqMeetingAdd) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqMeetingAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqMeetingAdd) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *ReqMeetingAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqMeetingAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqMeetingAdd) GetAppointed() string {
	if m != nil {
		return m.Appointed
	}
	return ""
}

func (m *ReqMeetingAdd) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *ReqMeetingAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyMeetingOne struct {
	Info                 *MeetingInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyMeetingOne) Reset()         { *m = ReplyMeetingOne{} }
func (m *ReplyMeetingOne) String() string { return proto.CompactTextString(m) }
func (*ReplyMeetingOne) ProtoMessage()    {}
func (*ReplyMeetingOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ac28e9a2c56839, []int{2}
}

func (m *ReplyMeetingOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMeetingOne.Unmarshal(m, b)
}
func (m *ReplyMeetingOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMeetingOne.Marshal(b, m, deterministic)
}
func (m *ReplyMeetingOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMeetingOne.Merge(m, src)
}
func (m *ReplyMeetingOne) XXX_Size() int {
	return xxx_messageInfo_ReplyMeetingOne.Size(m)
}
func (m *ReplyMeetingOne) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMeetingOne.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMeetingOne proto.InternalMessageInfo

func (m *ReplyMeetingOne) GetInfo() *MeetingInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyMeetingOne) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyMeetingList struct {
	Total                uint32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageMax              uint32         `protobuf:"varint,2,opt,name=pageMax,proto3" json:"pageMax,omitempty"`
	PageNow              uint32         `protobuf:"varint,3,opt,name=pageNow,proto3" json:"pageNow,omitempty"`
	List                 []*MeetingInfo `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyMeetingList) Reset()         { *m = ReplyMeetingList{} }
func (m *ReplyMeetingList) String() string { return proto.CompactTextString(m) }
func (*ReplyMeetingList) ProtoMessage()    {}
func (*ReplyMeetingList) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ac28e9a2c56839, []int{3}
}

func (m *ReplyMeetingList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyMeetingList.Unmarshal(m, b)
}
func (m *ReplyMeetingList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyMeetingList.Marshal(b, m, deterministic)
}
func (m *ReplyMeetingList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyMeetingList.Merge(m, src)
}
func (m *ReplyMeetingList) XXX_Size() int {
	return xxx_messageInfo_ReplyMeetingList.Size(m)
}
func (m *ReplyMeetingList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyMeetingList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyMeetingList proto.InternalMessageInfo

func (m *ReplyMeetingList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyMeetingList) GetPageMax() uint32 {
	if m != nil {
		return m.PageMax
	}
	return 0
}

func (m *ReplyMeetingList) GetPageNow() uint32 {
	if m != nil {
		return m.PageNow
	}
	return 0
}

func (m *ReplyMeetingList) GetList() []*MeetingInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyMeetingList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*MeetingInfo)(nil), "omo.msp.assignment.MeetingInfo")
	proto.RegisterType((*ReqMeetingAdd)(nil), "omo.msp.assignment.ReqMeetingAdd")
	proto.RegisterType((*ReplyMeetingOne)(nil), "omo.msp.assignment.ReplyMeetingOne")
	proto.RegisterType((*ReplyMeetingList)(nil), "omo.msp.assignment.ReplyMeetingList")
}

func init() {
	proto.RegisterFile("proto/assignment/meeting.proto", fileDescriptor_42ac28e9a2c56839)
}

var fileDescriptor_42ac28e9a2c56839 = []byte{
	// 666 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x4f, 0x4f, 0xdb, 0x4e,
	0x10, 0x8d, 0x63, 0x27, 0x90, 0x85, 0x84, 0xfc, 0x56, 0xfc, 0xd0, 0x2a, 0x2a, 0x6d, 0xea, 0xf6,
	0x90, 0x53, 0x90, 0xe0, 0xd0, 0x33, 0x1c, 0x40, 0x95, 0x0a, 0xad, 0x4c, 0xab, 0x4a, 0x55, 0x2f,
	0x26, 0x1e, 0xa2, 0x55, 0x6d, 0xaf, 0xf1, 0xae, 0xa1, 0x9c, 0xfa, 0xfd, 0x7a, 0xeb, 0xa7, 0xe8,
	0x07, 0xe8, 0x17, 0xa8, 0x66, 0xd6, 0x36, 0xe6, 0x4f, 0x20, 0xbd, 0xf9, 0xed, 0x9b, 0x7d, 0x33,
	0xef, 0xed, 0x40, 0xd8, 0xf3, 0x2c, 0x57, 0x46, 0xed, 0x84, 0x5a, 0xcb, 0x79, 0x9a, 0x40, 0x6a,
	0x76, 0x12, 0x00, 0x23, 0xd3, 0xf9, 0x94, 0x08, 0xce, 0x55, 0xa2, 0xa6, 0x89, 0xce, 0xa6, 0x37,
	0x15, 0xa3, 0xed, 0x7b, 0x77, 0x66, 0x2a, 0x49, 0x54, 0x6a, 0xaf, 0xf8, 0x7f, 0x5c, 0xb6, 0x76,
	0x6c, 0x45, 0xde, 0xa6, 0xe7, 0x8a, 0x0f, 0x99, 0x5b, 0xc8, 0x48, 0x38, 0x63, 0x67, 0xd2, 0x0b,
	0xf0, 0x93, 0x0f, 0x58, 0x5b, 0x46, 0xa2, 0x3d, 0x76, 0x26, 0x5e, 0xd0, 0x96, 0x11, 0x17, 0x6c,
	0x65, 0x96, 0x43, 0x68, 0x20, 0x12, 0xee, 0xd8, 0x99, 0xb8, 0x41, 0x05, 0x91, 0x29, 0xb2, 0x88,
	0x18, 0xcf, 0x32, 0x25, 0xac, 0xef, 0xa8, 0x5c, 0x74, 0x48, 0xb9, 0x82, 0x7c, 0xc4, 0x56, 0x55,
	0x06, 0x39, 0x51, 0x5d, 0xa2, 0x6a, 0xcc, 0xb7, 0x58, 0x57, 0x9b, 0xd0, 0x14, 0x5a, 0xac, 0x8c,
	0x9d, 0x49, 0x3f, 0x28, 0x11, 0xe7, 0xcc, 0x33, 0xd7, 0x19, 0x88, 0x55, 0x3a, 0xa5, 0x6f, 0xec,
	0xa0, 0x8d, 0xca, 0x32, 0x88, 0x44, 0xcf, 0xf6, 0x2e, 0xa1, 0x65, 0xc2, 0x1c, 0xa7, 0x62, 0x15,
	0x43, 0x90, 0x6f, 0xb2, 0x8e, 0xba, 0x4a, 0x21, 0x17, 0x6b, 0xd4, 0xd8, 0x02, 0x3c, 0x9d, 0xe7,
	0xaa, 0xc8, 0xc4, 0xba, 0x3d, 0x25, 0x80, 0x73, 0xc6, 0x6a, 0x16, 0x1a, 0xa9, 0x52, 0xd1, 0xb7,
	0x73, 0x56, 0x18, 0xb9, 0xa8, 0xc8, 0x2d, 0x37, 0xa0, 0x99, 0x6a, 0xcc, 0x9f, 0xb1, 0x5e, 0x98,
	0x65, 0x4a, 0xa6, 0xd8, 0x7f, 0x83, 0x2e, 0xde, 0x1c, 0xa0, 0x93, 0x34, 0x4c, 0x40, 0x0c, 0x89,
	0xa0, 0x6f, 0x74, 0x9d, 0x43, 0x12, 0xe6, 0xdf, 0xc4, 0x7f, 0x74, 0x5a, 0x22, 0x9c, 0x0b, 0x9f,
	0x50, 0x8b, 0xcd, 0xb1, 0x8b, 0x73, 0x11, 0x20, 0x77, 0xc5, 0x59, 0x22, 0x8d, 0x16, 0xff, 0xd3,
	0x79, 0x05, 0x71, 0xaa, 0x54, 0x19, 0x79, 0x2e, 0x41, 0x8b, 0x2d, 0xa2, 0x6a, 0xec, 0xff, 0x72,
	0x58, 0x3f, 0x80, 0x8b, 0xf2, 0xe1, 0xf7, 0xa3, 0xa8, 0xce, 0xd4, 0x69, 0x64, 0x5a, 0xe7, 0xd3,
	0x7e, 0x30, 0x1f, 0xb7, 0x99, 0x4f, 0xe5, 0xc4, 0x7b, 0xd0, 0x49, 0xe7, 0x96, 0x93, 0x5b, 0x99,
	0x74, 0xef, 0x66, 0xd2, 0x4c, 0x7a, 0xe5, 0x7e, 0xd2, 0xf5, 0xb6, 0xac, 0xde, 0xde, 0x16, 0xff,
	0x07, 0xdb, 0x08, 0x20, 0x8b, 0xaf, 0x4b, 0x53, 0xef, 0x53, 0xe0, 0x7b, 0xcc, 0x93, 0xe9, 0xb9,
	0x22, 0x53, 0x6b, 0xbb, 0x2f, 0xa6, 0xf7, 0xff, 0x3c, 0xa6, 0x8d, 0xdd, 0x0f, 0xa8, 0x98, 0xbf,
	0xa9, 0xb7, 0xae, 0xbd, 0xf8, 0x1a, 0x75, 0x3a, 0xa5, 0xb2, 0x6a, 0x2d, 0xfd, 0x9f, 0x0e, 0x1b,
	0x36, 0x27, 0x78, 0x27, 0xb5, 0xc1, 0xb4, 0x8c, 0x32, 0x61, 0x5c, 0x06, 0x6b, 0x01, 0xbe, 0x5a,
	0x16, 0xce, 0xe1, 0x38, 0xfc, 0x4e, 0x4d, 0xfa, 0x41, 0x05, 0x2b, 0xe6, 0x44, 0x5d, 0x51, 0xbe,
	0x25, 0x73, 0xa2, 0xae, 0xd0, 0x4c, 0x2c, 0xb5, 0x11, 0xde, 0xd8, 0x5d, 0xca, 0x0c, 0x16, 0x37,
	0xcc, 0x74, 0xfe, 0xc9, 0xcc, 0xee, 0x6f, 0x8f, 0x0d, 0x4a, 0xb9, 0x53, 0xc8, 0x2f, 0xe5, 0x0c,
	0x78, 0xc0, 0xba, 0xfb, 0x51, 0x84, 0xb9, 0xbe, 0x7c, 0x58, 0xa5, 0xb1, 0x4f, 0xa3, 0x57, 0x0b,
	0x1b, 0xdd, 0xbc, 0x8f, 0xdf, 0xe2, 0x1f, 0x58, 0xf7, 0x08, 0x0c, 0x6a, 0x2e, 0x98, 0xec, 0xa2,
	0x00, 0x6d, 0xd0, 0xd0, 0xb2, 0x8a, 0xc7, 0xac, 0x17, 0x40, 0xa2, 0x2e, 0x61, 0x29, 0xd1, 0xed,
	0x85, 0xa2, 0x48, 0xfb, 0x2d, 0xfe, 0x95, 0x6d, 0x1c, 0x81, 0xc1, 0xa7, 0x3c, 0xb8, 0x3e, 0x94,
	0xb1, 0x81, 0x7c, 0xa1, 0x7b, 0x14, 0xb5, 0x25, 0xa3, 0xd7, 0x4f, 0xcd, 0x8a, 0x82, 0x7e, 0x8b,
	0x7f, 0x66, 0xeb, 0x47, 0x60, 0x30, 0x7a, 0xa9, 0x8d, 0x9c, 0x2d, 0x23, 0xed, 0x3f, 0xfa, 0x82,
	0x24, 0xe3, 0xb7, 0xf8, 0x47, 0x36, 0xf8, 0x44, 0xff, 0x7b, 0x97, 0x9a, 0xda, 0x96, 0x3e, 0x1d,
	0xc6, 0x29, 0x5b, 0xb7, 0xa5, 0x76, 0x59, 0xb8, 0xff, 0x68, 0xbc, 0xe6, 0x30, 0x0e, 0xe7, 0x4f,
	0x8a, 0x1e, 0xf0, 0x2f, 0xc3, 0xbb, 0x3f, 0x51, 0x67, 0x5d, 0x3a, 0xd9, 0xfb, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x6a, 0x30, 0x3e, 0x21, 0xf1, 0x06, 0x00, 0x00,
}
