// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/assignment/team.proto

package assignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Id                   uint64   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string   `protobuf:"bytes,8,opt,name=owner,proto3" json:"owner,omitempty"`
	Remark               string   `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Master               string   `protobuf:"bytes,10,opt,name=master,proto3" json:"master,omitempty"`
	Assistants           []string `protobuf:"bytes,11,rep,name=assistants,proto3" json:"assistants,omitempty"`
	Tags                 []string `protobuf:"bytes,12,rep,name=tags,proto3" json:"tags,omitempty"`
	Members              []string `protobuf:"bytes,13,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamInfo) Reset()         { *m = TeamInfo{} }
func (m *TeamInfo) String() string { return proto.CompactTextString(m) }
func (*TeamInfo) ProtoMessage()    {}
func (*TeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{0}
}

func (m *TeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamInfo.Unmarshal(m, b)
}
func (m *TeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamInfo.Marshal(b, m, deterministic)
}
func (m *TeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamInfo.Merge(m, src)
}
func (m *TeamInfo) XXX_Size() int {
	return xxx_messageInfo_TeamInfo.Size(m)
}
func (m *TeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeamInfo proto.InternalMessageInfo

func (m *TeamInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TeamInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TeamInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeamInfo) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TeamInfo) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *TeamInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *TeamInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *TeamInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TeamInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *TeamInfo) GetMaster() string {
	if m != nil {
		return m.Master
	}
	return ""
}

func (m *TeamInfo) GetAssistants() []string {
	if m != nil {
		return m.Assistants
	}
	return nil
}

func (m *TeamInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TeamInfo) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type ReqTeamAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeamAdd) Reset()         { *m = ReqTeamAdd{} }
func (m *ReqTeamAdd) String() string { return proto.CompactTextString(m) }
func (*ReqTeamAdd) ProtoMessage()    {}
func (*ReqTeamAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{1}
}

func (m *ReqTeamAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeamAdd.Unmarshal(m, b)
}
func (m *ReqTeamAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeamAdd.Marshal(b, m, deterministic)
}
func (m *ReqTeamAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeamAdd.Merge(m, src)
}
func (m *ReqTeamAdd) XXX_Size() int {
	return xxx_messageInfo_ReqTeamAdd.Size(m)
}
func (m *ReqTeamAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeamAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeamAdd proto.InternalMessageInfo

func (m *ReqTeamAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqTeamAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTeamAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqTeamAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqTeamUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeamUpdate) Reset()         { *m = ReqTeamUpdate{} }
func (m *ReqTeamUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqTeamUpdate) ProtoMessage()    {}
func (*ReqTeamUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{2}
}

func (m *ReqTeamUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeamUpdate.Unmarshal(m, b)
}
func (m *ReqTeamUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeamUpdate.Marshal(b, m, deterministic)
}
func (m *ReqTeamUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeamUpdate.Merge(m, src)
}
func (m *ReqTeamUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqTeamUpdate.Size(m)
}
func (m *ReqTeamUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeamUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeamUpdate proto.InternalMessageInfo

func (m *ReqTeamUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqTeamUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTeamUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqTeamUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqTeamDevice struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Device               string   `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Type                 uint32   `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeamDevice) Reset()         { *m = ReqTeamDevice{} }
func (m *ReqTeamDevice) String() string { return proto.CompactTextString(m) }
func (*ReqTeamDevice) ProtoMessage()    {}
func (*ReqTeamDevice) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{3}
}

func (m *ReqTeamDevice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeamDevice.Unmarshal(m, b)
}
func (m *ReqTeamDevice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeamDevice.Marshal(b, m, deterministic)
}
func (m *ReqTeamDevice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeamDevice.Merge(m, src)
}
func (m *ReqTeamDevice) XXX_Size() int {
	return xxx_messageInfo_ReqTeamDevice.Size(m)
}
func (m *ReqTeamDevice) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeamDevice.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeamDevice proto.InternalMessageInfo

func (m *ReqTeamDevice) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqTeamDevice) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTeamDevice) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ReqTeamDevice) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ReqTeamDevice) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

type ReplyTeamInfo struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Info                 *TeamInfo    `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyTeamInfo) Reset()         { *m = ReplyTeamInfo{} }
func (m *ReplyTeamInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyTeamInfo) ProtoMessage()    {}
func (*ReplyTeamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{4}
}

func (m *ReplyTeamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTeamInfo.Unmarshal(m, b)
}
func (m *ReplyTeamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTeamInfo.Marshal(b, m, deterministic)
}
func (m *ReplyTeamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTeamInfo.Merge(m, src)
}
func (m *ReplyTeamInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyTeamInfo.Size(m)
}
func (m *ReplyTeamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTeamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTeamInfo proto.InternalMessageInfo

func (m *ReplyTeamInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyTeamInfo) GetInfo() *TeamInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type ReplyTeamList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*TeamInfo  `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyTeamList) Reset()         { *m = ReplyTeamList{} }
func (m *ReplyTeamList) String() string { return proto.CompactTextString(m) }
func (*ReplyTeamList) ProtoMessage()    {}
func (*ReplyTeamList) Descriptor() ([]byte, []int) {
	return fileDescriptor_28bce25f9dd8d840, []int{5}
}

func (m *ReplyTeamList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTeamList.Unmarshal(m, b)
}
func (m *ReplyTeamList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTeamList.Marshal(b, m, deterministic)
}
func (m *ReplyTeamList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTeamList.Merge(m, src)
}
func (m *ReplyTeamList) XXX_Size() int {
	return xxx_messageInfo_ReplyTeamList.Size(m)
}
func (m *ReplyTeamList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTeamList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTeamList proto.InternalMessageInfo

func (m *ReplyTeamList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyTeamList) GetList() []*TeamInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*TeamInfo)(nil), "omo.msp.assignment.TeamInfo")
	proto.RegisterType((*ReqTeamAdd)(nil), "omo.msp.assignment.ReqTeamAdd")
	proto.RegisterType((*ReqTeamUpdate)(nil), "omo.msp.assignment.ReqTeamUpdate")
	proto.RegisterType((*ReqTeamDevice)(nil), "omo.msp.assignment.ReqTeamDevice")
	proto.RegisterType((*ReplyTeamInfo)(nil), "omo.msp.assignment.ReplyTeamInfo")
	proto.RegisterType((*ReplyTeamList)(nil), "omo.msp.assignment.ReplyTeamList")
}

func init() {
	proto.RegisterFile("proto/assignment/team.proto", fileDescriptor_28bce25f9dd8d840)
}

var fileDescriptor_28bce25f9dd8d840 = []byte{
	// 605 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x76, 0x30, 0xe4, 0x06, 0xf2, 0xa1, 0xd1, 0x27, 0x34, 0x4a, 0x0b, 0x0d, 0x5e, 0x65,
	0x15, 0x2a, 0xba, 0xe8, 0x1a, 0x54, 0x15, 0x55, 0x2a, 0x2d, 0x32, 0xb4, 0x55, 0xbb, 0x1b, 0xe2,
	0x0b, 0x9a, 0x96, 0xf1, 0x18, 0xcf, 0x84, 0x8a, 0xee, 0xfa, 0x62, 0x7d, 0x8b, 0xbe, 0x4f, 0x35,
	0xd7, 0x76, 0x70, 0x20, 0x7f, 0x12, 0xd9, 0xcd, 0xfd, 0x3b, 0xe7, 0xcc, 0x9d, 0x23, 0x1b, 0x9e,
	0x65, 0xb9, 0xb6, 0x7a, 0x5f, 0x18, 0x23, 0xaf, 0x52, 0x85, 0xa9, 0xdd, 0xb7, 0x28, 0x54, 0x9f,
	0xb2, 0x8c, 0x69, 0xa5, 0xfb, 0xca, 0x64, 0xfd, 0xfb, 0x72, 0x67, 0xe7, 0xd1, 0xc0, 0x40, 0x2b,
	0xa5, 0xd3, 0x62, 0x24, 0xfa, 0xe3, 0xc3, 0xfa, 0x39, 0x0a, 0xf5, 0x2e, 0xbd, 0xd4, 0x6c, 0x0b,
	0x82, 0xa1, 0x4c, 0xb8, 0xd7, 0xf5, 0x7a, 0xcd, 0xd8, 0x1d, 0x59, 0x1b, 0x7c, 0x99, 0x70, 0xbf,
	0xeb, 0xf5, 0x1a, 0xb1, 0x2f, 0x13, 0xc6, 0xa0, 0x91, 0x0a, 0x85, 0x3c, 0xa0, 0x16, 0x3a, 0x33,
	0x0e, 0x6b, 0x83, 0x1c, 0x85, 0xc5, 0x84, 0x37, 0xba, 0x5e, 0x2f, 0x88, 0xab, 0xd0, 0x55, 0x86,
	0x59, 0x42, 0x95, 0xd5, 0xa2, 0x52, 0x86, 0xa3, 0x19, 0x9d, 0xf3, 0x90, 0xa0, 0xaa, 0x90, 0x75,
	0x60, 0x5d, 0x67, 0x98, 0x53, 0x69, 0x8d, 0x4a, 0xa3, 0x98, 0xfd, 0x0f, 0xab, 0xfa, 0x67, 0x8a,
	0x39, 0x5f, 0xa7, 0x42, 0x11, 0xb0, 0x6d, 0x08, 0x73, 0x54, 0x22, 0xff, 0xc1, 0x9b, 0x94, 0x2e,
	0x23, 0x97, 0x57, 0xc2, 0x58, 0xcc, 0x39, 0x14, 0xf9, 0x22, 0x62, 0xbb, 0x00, 0x6e, 0x1b, 0xc6,
	0x8a, 0xd4, 0x1a, 0xde, 0xea, 0x06, 0xbd, 0x66, 0x5c, 0xcb, 0xb8, 0x3b, 0x5a, 0x71, 0x65, 0xf8,
	0x06, 0x55, 0xe8, 0xec, 0xf4, 0x2a, 0x54, 0x17, 0x98, 0x1b, 0xbe, 0x49, 0xe9, 0x2a, 0x8c, 0xbe,
	0x03, 0xc4, 0x78, 0xe3, 0x56, 0x78, 0x98, 0x24, 0xf7, 0x0a, 0xbd, 0xba, 0xc2, 0x6a, 0x6b, 0x7e,
	0x6d, 0x6b, 0xf7, 0xaa, 0x83, 0x31, 0xd5, 0xf5, 0xfb, 0x37, 0xc6, 0xef, 0x1f, 0x49, 0xd8, 0x2c,
	0xb9, 0x3e, 0xd1, 0x1e, 0x27, 0x3c, 0xd8, 0xb2, 0xa8, 0x7e, 0x7b, 0x23, 0xae, 0x37, 0x78, 0x2b,
	0x07, 0x93, 0xb8, 0xea, 0xf3, 0xfe, 0x83, 0xa7, 0xda, 0x86, 0x30, 0xa1, 0xb9, 0x8a, 0xb3, 0x88,
	0x68, 0xb9, 0x77, 0x19, 0x12, 0xdf, 0x66, 0x4c, 0xe7, 0x9a, 0xbe, 0xd5, 0xba, 0xbe, 0xe8, 0x97,
	0x93, 0x90, 0x5d, 0xdf, 0x8d, 0xfc, 0xf9, 0x1a, 0x42, 0x63, 0x85, 0x1d, 0x1a, 0x52, 0xd1, 0x3a,
	0x78, 0xd1, 0x7f, 0x6c, 0xf8, 0x3e, 0x8d, 0x9c, 0x51, 0x5b, 0x5c, 0xb6, 0xb3, 0x97, 0xd0, 0x90,
	0xe9, 0xa5, 0x26, 0x95, 0xad, 0x83, 0xe7, 0x93, 0xc6, 0x2a, 0x92, 0x98, 0x3a, 0xc7, 0xb8, 0xdf,
	0x4b, 0x63, 0x9f, 0xc4, 0x7d, 0x2d, 0x8d, 0xe5, 0x7e, 0x37, 0x98, 0xcf, 0xed, 0x3a, 0x0f, 0xfe,
	0x86, 0xd0, 0x72, 0xa9, 0x33, 0xcc, 0x69, 0x67, 0x27, 0x10, 0x1e, 0x26, 0xc9, 0xc7, 0x14, 0xd9,
	0xee, 0x64, 0xd2, 0xca, 0x7e, 0x9d, 0xbd, 0xa9, 0xa2, 0x2a, 0x8a, 0x68, 0x85, 0x9d, 0x02, 0x14,
	0xf6, 0x39, 0x12, 0x06, 0xd9, 0xde, 0x0c, 0xc8, 0xa2, 0xad, 0xb3, 0x33, 0x15, 0xb5, 0x44, 0x3c,
	0x81, 0x66, 0x8c, 0x4a, 0xdf, 0xa2, 0xd3, 0x38, 0x65, 0x31, 0x37, 0x43, 0x34, 0xd6, 0xf5, 0xcf,
	0x87, 0xfb, 0x00, 0xe1, 0x31, 0xda, 0x85, 0xb0, 0x16, 0xba, 0xf0, 0x67, 0x68, 0x17, 0x78, 0x47,
	0x77, 0x6f, 0xe5, 0xb5, 0xfb, 0x04, 0x2c, 0x07, 0xf7, 0x2b, 0xfc, 0x77, 0x8c, 0xd6, 0xb9, 0x63,
	0x04, 0xbc, 0x37, 0x03, 0xb8, 0x68, 0x99, 0x03, 0xed, 0xd0, 0xa2, 0x15, 0xf6, 0x05, 0x36, 0x8e,
	0xd1, 0x3a, 0x27, 0x49, 0x63, 0xe5, 0x60, 0x11, 0xdc, 0x68, 0xa6, 0x21, 0x09, 0x26, 0x5a, 0x61,
	0xe7, 0xd0, 0x2e, 0x1f, 0x7f, 0x11, 0xc9, 0x8b, 0x1a, 0xe0, 0x14, 0x36, 0x0e, 0xb3, 0x0c, 0xd3,
	0xe4, 0x84, 0xbe, 0x8a, 0x4f, 0xf1, 0x40, 0xb9, 0x80, 0x18, 0xda, 0x67, 0xc3, 0x0b, 0x9b, 0x8b,
	0x81, 0x5d, 0x16, 0xe6, 0x11, 0xfb, 0xb6, 0xf5, 0xf0, 0x67, 0x78, 0x11, 0x52, 0xe6, 0xd5, 0xbf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x17, 0xff, 0xca, 0x58, 0x07, 0x00, 0x00,
}
